### ISSUE TITLE
build is broken

### ISSUE THREAD

**Issue by djlauk** [paulscherrerinstitute/databuffer-query-js#6]
The TypeScript build is broken.

```
npm run build

> @psi/databuffer-query-js@0.3.0 build /Users/lauk/coding/databuffer-query-js
> tsc --build tsconfig.json

src/query-channel-names/query.ts:66:14 - error TS2558: Expected 2 type arguments, but got 1.

66  return post<QueryResponse>(endpoint, options)
                ~~~~~~~~~~~~~

src/query-data/query.ts:77:20 - error TS2558: Expected 2 type arguments, but got 1.

77  return await post<QueryResponse>(endpoint, options)
                      ~~~~~~~~~~~~~


Found 2 errors.
```

**Comment by djlauk** [comment]
This broke when adding another type parameter for `post` in commit 5aa5f83f333cf1866d8867657a9729304a5f2b00
